# Create a docker-compose.yml file for multi-container management if you're running multiple services like ProductService or UserAuth Service:
version: "3.8"

services:
  userauth:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/superauth
      - JWT_SECRET=supersecretjwtkey
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongodb
      - redis  # Added Redis dependency

  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

volumes:
  mongodb_data:

networks:
  app_network:
    driver: bridge
