POST
http://localhost:5000/api/v1/auth/register

Body Json
{
  "firstName": "Alice",
  "lastName": "Johnson",
  "email": "alice@example.com",
  "password": "strongPassword123",
  "passwordConfirmation": "strongPassword123"
}


POST
http://localhost:5000/api/v1/auth/login


Body Json
{
  "email": "alice@example.com",
  "password": "strongPassword123"
}


POST
http://localhost:5000/api/v1/auth/logout


POST 
http://localhost:5000/api/v1/auth/refresh
Headers:
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MzQ1ZmVjMDM0ZTc0MTk0MjQyMGY2ZSIsImlhdCI6MTc0ODI2Mjk3NywiZXhwIjoxNzQ4ODY3Nzc3fQ.Vtn9yoxHS96GrxkhPQteC_TeEA1rzjQvxxQWCK_OrKo




POST
http://localhost:5000/api/v1/auth/refresh-access-token
Headers:
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MzQ1ZmVjMDM0ZTc0MTk0MjQyMGY2ZSIsImlhdCI6MTc0ODI2Mjk3NywiZXhwIjoxNzQ4ODY3Nzc3fQ.Vtn9yoxHS96GrxkhPQteC_TeEA1rzjQvxxQWCK_OrKo




POST
http://localhost:5000/api/v1/verify/verify-access-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MzQ1ZmVjMDM0ZTc0MTk0MjQyMGY2ZSIsImlhdCI6MTc0ODI2Mjk3NywiZXhwIjoxNzQ4ODY3Nzc3fQ.Vtn9yoxHS96GrxkhPQteC_TeEA1rzjQvxxQWCK_OrKo





POST
http://localhost:5000/api/v1/verify/verify-refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MzQ1ZmVjMDM0ZTc0MTk0MjQyMGY2ZSIsImlhdCI6MTc0ODI2Mjk3NywiZXhwIjoxNzQ4ODY3Nzc3fQ.Vtn9yoxHS96GrxkhPQteC_TeEA1rzjQvxxQWCK_OrKo
